# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e330ca95fde893b23d3cbbf541b8afed65ba33621d30c07367dc31ffe135d9332b686db285dd52dd0f1e05f7ff8815d60df5f2f4c0f03046954d72d59157a21c

test:
  secret_key_base: 794439ea0cfeed64cd3cfaca3e0c928d0c3d5f91c84b263029272754a5cfe1485044b836650eac438d960f59e7143764b6896379cac00b07f9526b9bbf691f7f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
